# Generated by Django 4.2.17 on 2025-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('moto_cliente', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(choices=[('revision', 'Revisión'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_general', 'Mantenimiento General'), ('otro', 'Otro')], max_length=100)),
                ('descripcion', models.TextField()),
                ('cobro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
